version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    "()": pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  error:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  json_error:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stderr
  json_default:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  recipe_generator:
    level: DEBUG
    handlers:
      - default
    propagate: no
  uvicorn.error:
    level: DEBUG
    handlers:
      - error
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers:
      - default
    propagate: no
